<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<!-- <nav class="customNavigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?//= /* @escapeNotVerified */ $_menu ?>
        <?//= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav> -->
<nav class="customNavigation" data-action="navigation">
    <ul>
        <li><a href="#">Tea</a></li>
        <li><a href="#">Gift Box</a></li>
        <li><a href="#">Subscriptions</a></li>
        <li><a href="#">Blog</a></li>
    </ul>
</nav>
