<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>


             <!--Custom code added START-->
             <?php 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
            $productz = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
            if($productz->getAttributeSetId() == 4){

            ?> 
            <div class="dividerTeaFloor" style="clear: both;"></div>
            <div class="conCenter">
            <h3 class="pageTitle">Know it, before you pour it.</h3>
            <p class="pageSubTitle">Hand crafted special Tea and Teaware</p>
            </div>
            <div class="productGrid">

            <?php
            // Dry Leafs
            $dry_leaf_image = $product->getCustomAttribute( 'dry_leaf_image' );
            $dry_leaf_imageURL = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'dry_leaf_image')->setImageFile($dry_leaf_image->getValue());
            if(!empty($dry_leaf_imageURL->getURL()) && !empty($productz->getData('dry_leaf_text'))){ ?>
                <div class="innerProductWrapper">
                    <div class="innerProductImg"><img src="<?php echo $dry_leaf_imageURL->getURL();?>" alt="test"></div>
                    <div class="innerProductTitle"><h4>Dry Leaf</h4><p><?php echo $productz->getData('dry_leaf_text');?></p></div>
                </div>
            <?php } ?>

            <?php
            // Dry Leafs
            $infusion_image = $product->getCustomAttribute( 'infusion_img' );
            $infusion_imageURL = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'infusion_img')->setImageFile($infusion_image->getValue());
            if(!empty($infusion_imageURL->getURL()) && !empty($productz->getData('infusion'))){ ?>
                <div class="innerProductWrapper">
                    <div class="innerProductImg"><img src="<?php echo $infusion_imageURL->getURL();?>" alt="test"></div>
                    <div class="innerProductTitle"><h4>Infusion</h4><p><?php echo $productz->getData('infusion');?></p></div>
                </div>
            <?php } ?>

            <?php
            // Dry Leafs
            $liquor_img = $product->getCustomAttribute( 'liquor_img' );
            $liquor_imageURL = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'liquor_img')->setImageFile($liquor_img->getValue());
            if(!empty($liquor_imageURL->getURL()) && !empty($productz->getData('liquor'))){ ?>
                <div class="innerProductWrapper">
                    <div class="innerProductImg"><img src="<?php echo $liquor_imageURL->getURL();?>" alt="test"></div>
                    <div class="innerProductTitle"><h4>Liquor</h4><p><?php echo $productz->getData('liquor');?></p></div>
                </div>
            <?php } ?>
            </div>
            <br>
            <div class="dividerTeaFloor"></div>
            <br>
            <div class="conCenter">
                <h3 class="pageTitle">Steeping Notes</h3>
                <p class="pageSubTitle">Hand crafted special Tea and Teaware</p>
            </div>

            <div class="productFoot">
                <div class="productFootInner">
                    <h5>Details</h5>
                    <p><?php echo $productz->getData('details_for_product');?></p>
                </div>
                <div class="productFootInner">
                    <h5>Ingredients</h5>
                    <p><?php echo $productz->getData('ingredients_product');?></p>
                </div>
                <div class="productFootInner">
                    <h5>Pairing Notes</h5>
                    <p><?php echo $productz->getData('pairing_notes_products');?></p>
                </div>
            </div>
            <br>
            <br>
            <div class="dividerTeaFloor"></div>
            <br>
            <?php                 
            }elseif($productz->getAttributeSetId() == 11){ ?>
                <div class="dividerTeaFloor" style="clear: both;"></div>
                <div class="conCenter">
                <h3 class="pageTitle">Inside the Box</h3>
                <p class="pageSubTitle">Hand crafted special Tea and Teaware</p>
                </div>
                <div class="productGridCol">
                    <?php 
                    $itb_total_variation = $productz->getData( 'itb_total_variation' );
                    $attr = $product->getResource()->getAttribute('itb_total_variation');
                    if ($attr->usesSource()) {
                        $optionCount = $attr->getSource()->getOptionText($itb_total_variation);
                    }
                    for ($i=1; $i <= $optionCount; $i++) { ?>
                        <div class="boxItem" >
                            <div class="boxItemImage">
                                <?php
                                    $itb_title = $product->getCustomAttribute( 'itb_image_'.$i );
                                    $itb_title_imageURL = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'itb_image_'.$i)->setImageFile($itb_title->getValue());
                                ?>
                                <img src="<?php echo $itb_title_imageURL->getURL(); ?>" alt="">
                            </div>
                            <div class="boxItemTitle">
                                <?php echo $productz->getData( 'itb_title_'.$i ); ?>
                            </div>
                            <div class="boxItemGram">
                                <?php echo $productz->getData( 'itb_weight_'.$i ); ?>
                            </div>
                        </div>
                    <?php } ?>
                    
                    
                </div>
                <br>
            <br>
            <div class="dividerTeaFloor"></div>
            <br>
            <?php }else{

            }
            ?>
            <!--Custom code added END-->



            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
           
        </div>
    </div>
    <br>
    <div class="dividerTeaFloor"></div>
    <br>
    <div class="conCenter">
        <h3 class="pageTitle">As Seen On Instagram</h3>
    </div>
    <?php 
    $instImg = preg_split('/\r\n|[\r\n]/',$productz->getData('instagram'));
    print_r($instImg);
    ?>
    

<p class="imglist" style="max-width: 1000px;">
  <a href="https://source.unsplash.com/juHayWuaaoQ/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/juHayWuaaoQ/240x160" />
  </a>

  <a href="https://source.unsplash.com/eWFdaPRFjwE/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/eWFdaPRFjwE/240x160" />
  </a>

  <a href="https://source.unsplash.com/i2KibvLYjqk/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/i2KibvLYjqk/240x160" />
  </a>

  <a href="https://source.unsplash.com/RFgO9B_OR4g/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/RFgO9B_OR4g/240x160" />
  </a>

  <a href="https://source.unsplash.com/7bwQXzbF6KE/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/7bwQXzbF6KE/240x160" />
  </a>

  <a href="https://source.unsplash.com/NhU0nUR7920/1500x1000" data-fancybox="images">
    <img src="https://source.unsplash.com/NhU0nUR7920/240x160" />
  </a>
</p>



     <br>
    <div class="dividerTeaFloor"></div>
    <br>
    <div class="conCenter">
        <h3 class="pageTitle">Our Customers Around The World</h3>
        <p class="pageSubTitle">Hand Crafted Special Tea</p>
    </div>
    <div>
    <img style="display: block; margin-left: auto; margin-right: auto;" src="<?php echo str_replace('index.php/','',$this->getUrl());?>media/wysiwyg/bottomGarden.png" alt="" />
    </div>
<?php endif; ?>
