<?php /** @var \Algolia\AlgoliaSearch\Block\Instant\Wrapper $block */ ?>

<!-- Wrapping template -->
<script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
        <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}

    <div id="algolia_instant_selector"
         class="<?php echo $block->escapeHtml($block->hasFacets() ? ' with-facets' : ''); ?>">
        <div class="row">
            <div class="col-md-3" id="algolia-left-container">
                <div id="refine-toggle" class="visible-xs visible-sm">
                    + <?php echo $block->escapeHtml(__('Refine')); ?>
                </div>
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container">
                    <div id="current-refinements"></div>
                </div>
            </div>

            <div class="col-md-9" id="algolia-right-container">
                <div class="row">
                    <div class="col-md-12">
                        <?php
                        //category images
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
                        if($category){
                            echo "<div class='catBreadcrumbs'>".$this->getLayout()->getBlock('breadcrumbs')->toHtml()."</div>";
                            ?>

                            <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
                                <span class="base" data-ui-id="page-title-wrapper"><?php echo $category->getName(); ?></span>
                            </h1>
                            <p><?php echo $category->getDescription(); ?></p>
                        <?php } ?>
                        
                        <div>
                            {{#second_bar}}
                            <div id="instant-search-bar-container">
                                <div id="instant-search-box">
                                    <div class="instant-search-bar-label">
                                        <span><?php echo $block->escapeHtml(__('Current search')); ?></span>
                                    </div>
                                    <div class="instant-search-bar-wrapper">
                                        <label for="instant-search-bar">
                                            <?php echo $block->escapeHtml(__('Search :')); ?>
                                        </label>

                                        <input placeholder="<?php echo $block->escapeHtml(__('Search for products')) ?>"
                                               id="instant-search-bar"
                                               type="text"
                                               autocomplete="off"
                                               spellcheck="false"
                                               autocorrect="off"
                                               autocapitalize="off" />
                                    </div>
                                </div>
                            </div>
                            {{/second_bar}}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div>
                        <div class="hits">
                            <div class="infos">
                                <div class="pull-left" id="algolia-stats"></div>
                                <div class="pull-right">
                                    <div class="sort-by-label pull-left">
                                        <?php echo $block->escapeHtml(__('SORT BY')); ?>
                                    </div>
                                    <div class="pull-left" id="algolia-sorts"></div>
                                </div>
                                <div class="algolia-clearfix"></div>
                            </div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                    <div class="algolia-clearfix"></div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="dividerTeaFloor"></div>
    <div class="conCenter">
        <h3 class="pageTitle">Authenticity is necessary</h3>
    </div>
    <br>
    <div>
    <img style="display: block; margin-left: auto; margin-right: auto;" src="<?php echo str_replace('index.php/','',$this->getUrl());?>media/wysiwyg/bottomGarden.png" alt="" />
    </div>
    <br>
    <br>
    <br>
    <br>
</script>